In [92]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

In [93]:
data = pd.read_csv("air_quality.csv")

In [94]:
data

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,3/10/2004,18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,3/10/2004,19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,3/10/2004,20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,3/10/2004,21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,3/10/2004,22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,4/4/2005,10:00:00,3.1,1314,-200,13.5,1101,472,539,190,1374,1729,21.9,29.3,0.7568
9353,4/4/2005,11:00:00,2.4,1163,-200,11.4,1027,353,604,179,1264,1269,24.3,23.7,0.7119
9354,4/4/2005,12:00:00,2.4,1142,-200,12.4,1063,293,603,175,1241,1092,26.9,18.3,0.6406
9355,4/4/2005,13:00:00,2.1,1003,-200,9.5,961,235,702,156,1041,770,28.3,13.5,0.5139
9356,4/4/2005,14:00:00,2.2,1071,-200,11.9,1047,265,654,168,1129,816,28.5,13.1,0.5028

In [95]:
data.drop(columns=["Date", "Time"], inplace=True)

In [96]:
data.drop_duplicates(inplace=True)

In [97]:
data.isna()

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,False,False,False,False,False,False,False,False,False,False,False,False,False
9353,False,False,False,False,False,False,False,False,False,False,False,False,False
9354,False,False,False,False,False,False,False,False,False,False,False,False,False
9355,False,False,False,False,False,False,False,False,False,False,False,False,False
9356,False,False,False,False,False,False,False,False,False,False,False,False,False

In [98]:
data.dropna(inplace=True)

In [99]:
data2 = pd.read_csv("heart.csv")

In [100]:
data = pd.concat([data,data2["chol"]], axis=1)

In [101]:
data.head()

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,chol
0,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578,212.0
1,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255,203.0
2,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502,174.0
3,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867,203.0
4,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888,294.0

In [102]:
scaler = MinMaxScaler()
num_cols = data.select_dtypes(include=[np.number]).columns
data[num_cols] = scaler.fit_transform(data[num_cols]);

In [103]:
data = pd.get_dummies(data, drop_first=True)

In [104]:
if "T" in data.columns:
    data = data[data["T"] > 0];

In [105]:
data

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,chol
0,0.956111,0.696429,0.251980,0.803565,0.516156,0.217987,0.435657,0.579630,0.635966,0.539111,0.873262,0.862141,0.992715,0.196347
1,0.953280,0.666071,0.224622,0.794084,0.478459,0.180465,0.476587,0.540741,0.591261,0.430408,0.872036,0.857984,0.992556,0.175799
2,0.954224,0.715179,0.207343,0.792567,0.471831,0.197141,0.464794,0.581481,0.589916,0.467866,0.866312,0.879806,0.992678,0.109589
3,0.954224,0.703571,0.201584,0.793326,0.475559,0.221560,0.448144,0.596296,0.599664,0.515241,0.862633,0.900589,0.992858,0.175799
4,0.951392,0.657143,0.180706,0.783087,0.429163,0.197141,0.487340,0.585185,0.568067,0.481087,0.863451,0.899203,0.992869,0.383562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,0.958471,0.675893,0.000000,0.809632,0.538940,0.400238,0.256330,0.722222,0.529076,0.708410,0.907195,0.794250,0.992710,NaN
9353,0.955168,0.608482,0.000000,0.801669,0.508285,0.329363,0.278876,0.701852,0.492101,0.539479,0.917007,0.774853,0.992488,NaN
9354,0.955168,0.599107,0.000000,0.805461,0.523198,0.293627,0.278529,0.694444,0.484370,0.474477,0.927637,0.756148,0.992136,NaN
9355,0.953752,0.537054,0.000000,0.794463,0.480944,0.259083,0.312869,0.659259,0.417143,0.356225,0.933361,0.739522,0.991509,NaN
9356,0.954224,0.567411,0.000000,0.803565,0.516570,0.276951,0.296219,0.681481,0.446723,0.373118,0.934178,0.738136,0.991454,NaN

In [106]:
num_cols = data.select_dtypes(include=[np.number]).columns
Q1 = data[num_cols].quantile(0.25)
Q3 = data[num_cols].quantile(0.75)
IQR = Q3 - Q1

# 3. Define lower and upper bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# 4. Remove outliers
data = data[
    ~((data[num_cols] < lower_bound) | (data[num_cols] > upper_bound)).any(axis=1)
]

In [107]:
data

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,chol
184,0.965078,0.811161,0.0,0.839211,0.635046,0.326980,0.307319,0.648148,0.742857,0.741462,0.890433,0.833045,0.993028,0.415525
185,0.957055,0.746875,0.0,0.812666,0.549710,0.252531,0.357614,0.651852,0.656134,0.649284,0.902698,0.811915,0.993104,0.372146
186,0.954224,0.704911,0.0,0.805840,0.525269,0.220965,0.381200,0.627778,0.626218,0.578039,0.914963,0.790440,0.993032,0.093607
187,0.954224,0.707589,0.0,0.804702,0.520298,0.207862,0.378425,0.616667,0.621176,0.539111,0.916599,0.792172,0.993179,0.280822
188,0.954696,0.704911,0.0,0.808115,0.533140,0.200715,0.381894,0.603704,0.625210,0.493573,0.920687,0.779009,0.992839,0.292237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,0.958471,0.675893,0.0,0.809632,0.538940,0.400238,0.256330,0.722222,0.529076,0.708410,0.907195,0.794250,0.992710,NaN
9353,0.955168,0.608482,0.0,0.801669,0.508285,0.329363,0.278876,0.701852,0.492101,0.539479,0.917007,0.774853,0.992488,NaN
9354,0.955168,0.599107,0.0,0.805461,0.523198,0.293627,0.278529,0.694444,0.484370,0.474477,0.927637,0.756148,0.992136,NaN
9355,0.953752,0.537054,0.0,0.794463,0.480944,0.259083,0.312869,0.659259,0.417143,0.356225,0.933361,0.739522,0.991509,NaN
9356,0.954224,0.567411,0.0,0.803565,0.516570,0.276951,0.296219,0.681481,0.446723,0.373118,0.934178,0.738136,0.991454,NaN

In [112]:
data = data.fillna(data.mean(numeric_only=True))
data = data.fillna("Unknown")

In [113]:
x = data.drop(columns=["AH"])
y = data["AH"]

In [114]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [115]:
model = LinearRegression()

In [116]:
model.fit(x_train,y_train)

LinearRegression()

In [117]:
y_pred = model.predict(x_test)

In [118]:
r2_score = r2_score(y_test,y_pred)
print(r2_score)

0.9192220483977765

In [120]:
mse = mean_squared_error(y_test,y_pred)
print(mse)

3.3563804921235415e-07